language: node_js
node_js:
  - '6'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -f median.sql -U postgres
env:
  - PG_USER=postgres PG_DATABASE=travis_ci_test PGHOST=localhost
