language: node_js
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
services:
  - postgresql
env:
  - PGUSER=postgres
  - PGDATABASE=travis_ci_test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
