language: node_js
node_js:
  - '6'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE OR REPLACE FUNCTION _final_median(NUMERIC[]) RETURNS NUMERIC AS $$ SELECT AVG(val) FROM (SELECT val FROM unnest($1) val ORDER BY 1 LIMIT  2 - MOD(array_upper($1, 1), 2) OFFSET CEIL(array_upper($1, 1) / 2.0) - 1) sub; $$ LANGUAGE 'sql' IMMUTABLE; CREATE AGGREGATE median(NUMERIC) (SFUNC=array_append, STYPE=NUMERIC[], FINALFUNC=_final_median, INITCOND='{}');" -U postgres
env:
  - PG_USER=postgres PG_DATABASE=travis_ci_test PGHOST=localhost
